task: sample
onnx:
  model_path: onnx/unit/test/sign.onnx  #onnx/unit/onnx_layers/matmul512_add.onnx
  input_path: #input_json/input_match_GWB.json
ptau:
  ptau_path: challenge_0022
  pow_len_log: 22
  loaded_pow_len_log: 14
sf:
  scale_factor_log: 4
  cq_range_log: 13
  cq_range_lower_log: 12
prover:
  model_path: models
  setup_path: setups
  enc_model_path: modelsEnc
  enc_input_path: inputsEnc
  enc_output_path: outputsEnc
  proof_path: proofs
  acc_proof_path: acc_proofs
  final_proof_path: final_proofs
  enable_layer_setup: true
verifier:
  enc_model_path: modelsEnc
  enc_input_path: inputsEnc
  enc_output_path: outputsEnc
  proof_path: proofs
